"""
Django settings for bookmarks project.

This file contains all the configuration for the Django project including:
- Installed apps
- Middleware
- Database settings
- Authentication backends
- Social login configuration
- Static and media files
- Redis and other services

Generated by 'django-admin startproject' using Django 4.2.1.
"""

from pathlib import Path
from django.urls import reverse_lazy

# Base directory of the project
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY SETTINGS
# Secret key for cryptographic signing – keep this safe in production!
SECRET_KEY = 'django-insecure-5_v*(mu&$)zpxejdae2l@l)$p&u0y$n!d3(dj-#$5#!4p0fz3('

# Debug mode – should be False in production
DEBUG = True

# Hosts/domain names that can serve this project
ALLOWED_HOSTS = ['mysite.com', 'localhost', '127.0.0.1']

# APPLICATIONS
INSTALLED_APPS = [
    # Custom apps
    'account.apps.AccountConfig',
    'images.apps.ImagesConfig',
    'actions.apps.ActionsConfig',
    
    # Django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'social_django',          # Social authentication
    'django_extensions',      # Extra management commands
    'easy_thumbnails',        # Image thumbnailing
    'debug_toolbar'           # Debugging toolbar
]

# MIDDLEWARE
MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',  # Adds debug toolbar to all responses
    'django.middleware.security.SecurityMiddleware',    # Security-related middleware
    'django.contrib.sessions.middleware.SessionMiddleware',  # Session management
    'django.middleware.common.CommonMiddleware',        # Common HTTP functionalities
    'django.middleware.csrf.CsrfViewMiddleware',        # CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Authentication
    'django.contrib.messages.middleware.MessageMiddleware',  # Flash messages
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Protects against clickjacking
]

# ROOT URL Configuration
ROOT_URLCONF = 'bookmarks.urls'

# TEMPLATE SETTINGS
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Project-level template directories
        'APP_DIRS': True,  # Include app-level templates automatically
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',      # Add debug context variables
                'django.template.context_processors.request',    # Add request to templates
                'django.contrib.auth.context_processors.auth',   # Add user auth context
                'django.contrib.messages.context_processors.messages',  # Add messages context
            ],
        },
    },
]

# WSGI Application
WSGI_APPLICATION = 'bookmarks.wsgi.application'

# DATABASE CONFIGURATION
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Using SQLite for development
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# PASSWORD VALIDATION
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# INTERNATIONALIZATION
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# STATIC FILES (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# DEFAULT PRIMARY KEY FIELD TYPE
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# LOGIN REDIRECTION
LOGIN_REDIRECT_URL = 'dashboard'  # Redirect after successful login
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'

# EMAIL BACKEND (console backend for development)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# MEDIA FILES
MEDIA_URL = 'media/'  # URL prefix for media files
MEDIA_ROOT = BASE_DIR / 'media'  # Filesystem location

# AUTHENTICATION BACKENDS
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default backend
    'account.authentication.EmailAuthBackend',    # Custom backend for email login
    'social_core.backends.facebook.FacebookOAuth2',  # Facebook OAuth2
    'social_core.backends.twitter.TwitterOAuth',     # Twitter OAuth
]

# FACEBOOK SOCIAL AUTH SETTINGS
SOCIAL_AUTH_FACEBOOK_KEY = '1221197148594832'
SOCIAL_AUTH_FACEBOOK_SECRET = '3a9278a2108b6497bc078a3157649c15'
# Optional scope for email: SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']

# SOCIAL AUTH PIPELINE
# Defines the sequence of functions executed during social login/signup
SOCIAL_AUTH_PIPELINE = [
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'account.authentication.create_profile',  # Custom profile creation
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
]

# URL OVERRIDES FOR AUTH.USER
# Redirect user objects to the user_detail view by username
ABSOLUTE_URL_OVERRIDES = {
    'auth.user': lambda u: reverse_lazy('user_detail', args=[u.username])
}

# INTERNAL IPs (for debug toolbar)
INTERNAL_IPS = ['127.0.0.1']

# REDIS SETTINGS (for caching, Celery, etc.)
REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 0
